#DEFINIMOS EL TIPO DE BASE DE DATOS
quarkus.datasource.db-kind=postgresql

#USUARIO CON EL Q SE CONECTA EN LA BASE DE DATOS 
quarkus.datasource.username=postgres
#PASSWORD
quarkus.datasource.password=Polar3

#url de conexion a la base de datos
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pa4bd

# = update sincroniza la base de datos sincroniza cuando hubo una actualizaacion en el codigo no ejecuta nada en la base de datos 
# = drop borra todo y reinicia vuelve a ejecutar la sentencia e inicia el insert de nuevo 
quarkus.hibernate-orm.database.generation=update

#
#quarkus.hibernate-orm.sql-load-script=import.sql

#se muestre en consola de quarkus para todo el codigo q ejecutemos se cree en la base 
quarkus.hibernate-orm.log.sql=true

